baseURL = 'https://panc.codeberg.page'
locale = 'zh-CN'
title = "panic"
theme = 'paper-lite'

[params]
[params.author]
email = 'pan0xc@foxmail.com'
name = 'Chen Pan'
avatar = 'https://blog.chenpan.me/avatar.svg'
bio = '选择一个难到几乎无人看好的项目，带着那种“我 偏要证明给他们看”的冲劲去完成。'

[menu]
[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 1
[[menu.main]]
identifier = "contact"
name = "Contact"
pageRef = "/contact"
weight = 2

[pagination]
pagerSize = 5

[markup]
[markup.highlight]
style = "tokyonight-night"
lineNos = true
lineNumbersInTable = false
