on: [push]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.159.0'
          extended: true

      - name: build
        run: |
          hugo --minify
          cp .domains public/.domains
      - uses: actions/git-pages@v2
        with:
          site: "https://panc.codeberg.page"
          token: ${{ forge.token }}
          source: public/